### ISSUE TITLE
You can't shoot over water.

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder-old#188]
Make it possible to shoot over the water.
It's not like shooting over water will make your arrows fall out of the sky.

**Comment by maitian352** [comment]
What about the waterbook glitch?

**Comment by definitely-nobody-is-here** [comment]
the waterbook glitch also works on buildings and trees.

**Comment by definitely-nobody-is-here** [comment]
add another layer in the tilemap and make it only apply to bullets, so you have a layer for players and a layer for bullets.

**Comment by definitely-nobody-is-here** [comment]
hurry up

**Comment by maitian352** [comment]
yes you can
